### PR TITLE
Throw if request canceled and received incomplete response

### LINKED ISSUE #748: Got returning response before retries
#### Describe the bug

 - Node.js version:  v11.3.0
 - OS & version: MacOs v11.3.0

#### Actual behavior

got return response before retry

```
[Downloaded] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
[Retry] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
[Retry] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
[Retry] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
```

#### Expected behavior

got should do all retries before returning response

#### Code to reproduce

```
const got = require('got');
const fs = require('fs');

async function test() {
    const url = 'http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg';
    const resp = await got(url, {
        timeout: {
            request: 1e3,
        },
        retry: 3,
        hooks: {
            beforeRetry: [(opt, err, retryN) => {
                console.log("[Retry]", opt.href)
            }]
        }
    });

    console.log('[Downloaded]', url);

    fs.createWriteStream('img').write(resp.body)
}

test();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #748

### CODE REVIEW

File: source/request-as-event-emitter.ts [hunk 1]
```diff
@@ -120,6 +124,21 @@ export default (options, input?: TransformStream) => {
 					gotOptions: options
 				};
 
+				// Cached requests don't have the request object (so we can't do `request.aborted`)
+				// so we need to create our own `canceled` property.
```
Comment (szmarczak) [inline source/request-as-event-emitter.ts]: Are cached requests cancelable? :confused:

File: source/as-promise.ts [hunk 2]
```diff
@@ -40,6 +40,11 @@ export default function asPromise(options: Options) {
 				return;
 			}
 
+			if (response.canceled()) {
```
Comment (szmarczak) [inline source/as-promise.ts]: If the cached requests are not cancelable we could simply do `if (response.req && response.req.aborted) {`

File: source/as-stream.ts [hunk 3]
```diff
@@ -23,7 +23,15 @@ export default function asStream(options: MergedOptions) {
 	const emitter = requestAsEventEmitter(options, input);
 
 	// Cancels the request
-	proxy._destroy = emitter.abort;
+	proxy._destroy = (error, callback) => {
+		// Stop transmitting data,
+		// so the stream won't have an `end` event.
+		output.destroy();
```
Comment (szmarczak) [inline source/as-stream.ts]: The more elegant way would be to unpipe the response.

Comment (szmarczak) [reply source/as-stream.ts]: We don't have to care about it. It will end if no error is provided, otherwise it will throw before ending.

File: source/as-promise.ts [hunk 4]
```diff
@@ -40,6 +40,11 @@ export default function asPromise(options: Options) {
 				return;
 			}
 
+			if (response.req && response.req.aborted) {
+				// Canceled while downloading - will throw a CancelError or TimeoutError
```
Comment (tobenna) [inline source/as-promise.ts]:
```suggestion
				// Cancelled while downloading - will throw a CancelError or TimeoutError
```

File: test/helpers/slow-data-stream.ts [hunk 5]
```diff
@@ -0,0 +1,18 @@
+import {PassThrough} from 'stream';
+
+export default () => {
```
Comment (tobenna) [inline test/helpers/slow-data-stream.ts]: It'll be nice to add an explicit return type here so it's once less thing we have to add when making the typescript types better.
```suggestion
export default (): PassThrough => {
```

File: source/as-promise.ts (hunk 4 above)
Comment (szmarczak) [reply source/as-promise.ts]: https://github.com/sindresorhus/p-cancelable/blob/master/readme.md#cancelable-vs-cancellable :smiley:

**Comment by szmarczak** [comment]
Thanks for the review @tobenna 🎉

It's very nice that you've had some time to take a look at this :)
