### PR TITLE
Fix EventEmitter memory leak

### LINKED ISSUE #399: Socket recycling causes memory leaks
If sockets are recycled, in our case because we're using [`agentkeepalive`](https://www.npmjs.com/package/agentkeepalive) as the agent, `got`'s listeners don't always get removed from the socket after it's done its thing. We validated this by instrumenting [the `connect` listener](https://github.com/sindresorhus/got/blob/1b8c1d6cc2981dffd12babf48ae8a2431bfbf619/index.js#L219) to store a unique ID on every new request ...

```js
// At the top
let count = 0

// In requestAsEventEmitter()
req.connection.on('connect', () => {
  req.connection.__id = req.connection.__id || ++count
  console.log('connect', req.connection.__id)
```

... and then firing a few requests in sequence using the same socket:

```js
const got = require('got')
const Agent = require('agentkeepalive')

const agent = new Agent({timeout: 100, maxSockets: 1})

;(async () => {
  for (let i = 0; i < 3; i++) {
    await got('http://localhost:31337', {agent})
  }
})()
```

For the first request, the socket connection listener is hit once; for the second, twice; for the third, thrice; etc. So clearly, something isn't getting cleaned up.

Of course, creating lots of internal state that isn't garbage-collected creates quite a big issue. So unless we're missing something, perhaps it should be made clear that recycling sockets isn't supported for the time being. In the longer term, `got` should probably clean up after itself even if the socket isn't disposed.

This wasn't the case with version 6, so presumably, since version 7, one of the closures in `requestAsEventEmitter()` is leaky. In general, personally, I'm a fan of using `.once()` where possible, and calling `.removeEventListener()` explicitly whenever I can. I feel like that would also be the more prudent approach here.

This was originally reported by @pietermees as part of his investigation for #353. The `EventEmitter` leak warning there actually wasn't a red herring at all.

Thanks!

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #399 // @timdp

Currently, when you run the Got tests it outputs warnings about EventEmitter memory leaks.

Tip: Run the tests with `NODE_OPTIONS=--trace-warnings ava` to see the stack trace of the warnings

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -220,7 +220,7 @@ function requestAsEventEmitter(opts) {
 				ee.emit('error', new got.RequestError(err, opts));
 			});
 
-			ee.on('request', req => {
+			ee.once('request', req => {
```
Comment (sindresorhus) [inline index.js]: This is the offending line. The other ones are just safeguarding for future memory leaks.

File: index.js [hunk 2]
```diff
@@ -198,15 +198,15 @@ function requestAsEventEmitter(opts) {
 			});
 		});
 
-		cacheReq.on('error', err => {
+		cacheReq.once('error', err => {
```
Comment (lukechilds) [inline index.js]: `cacheable-request` could potentially emit more than one error. These should be passed through.

File: index.js [hunk 3]
```diff
@@ -347,10 +347,10 @@ function asPromise(opts) {
 				});
 		});
 
-		ee.on('error', reject);
+		ee.once('error', reject);
```
Comment (lukechilds) [inline index.js]: This is fine, we can only reject once, so we should do it on the first error.

File: index.js [hunk 4]
```diff
@@ -427,8 +427,8 @@ function asStream(opts) {
 		proxy.emit('response', res);
 	});
 
+	ee.once('error', proxy.emit.bind(proxy, 'error'));
```
Comment (lukechilds) [inline index.js]: `cacheable-request` could potentially emit more than one error. These should be passed through.

File: index.js (hunk 1 above)
Comment (lukechilds) [reply index.js]: Yep, all good.

**Comment by timdp** [comment]
This is awesome. Thanks, guys!
