### PR TITLE
Make sure stream body errors are caught

### LINKED ISSUE #887: Doesn't catch `body` (Stream) errors
How do I prevent my app from crashing when posting a stream to an offline destination? In both examples below I get: 
```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:2024
    at TCPConnectWrap.afterConnect
```

(I'm on node v12.1.0)

```javascript
import FormData from 'form-data';
import got from 'got';
import fs from 'fs';

(async () => {
  try {
    const form = new FormData();
    form.append('upload', fs.createReadStream('filepath.jpg'));
    await got.post('http://offlinesite123.com', {
      body: form,
    });
  } catch (err) {
    console.error('does not catch', err);
  }
})();
```

this also crashes my app

```javascript
try {
  const form = new FormData();
  form.append('upload', fs.createReadStream('filepath.jpg'));
  got.stream
    .post('http://offlinesite123.com', {
      body: form,
    })
    .on('error', err => console.error('this error gets reported but app still crashes'));
} catch (err) {
  console.error('does not catch', err);
}
```

#### Checklist

- [x] I have read the documentation.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #887

### CODE REVIEW

File: test/stream.ts [hunk 1]
```diff
@@ -255,6 +258,14 @@ test('piping to got.stream.put()', withServer, async (t, server, got) => {
...
-// Do not remove this. Some test is throwing a unhandled rejection and we need to know what particular test does that.
-// (It will log the test name in Got options)
-process.on('unhandledRejection', console.log);
+test('no unhandled body stream errors', async t => {
+	const form = new FormData();
+	// @ts-ignore
+	form.append('upload', fs.createReadStream('/bin/sh'));
+
+	await t.throwsAsync(got.post(`https://offlinesite${Date.now()}.com`, {
+		form
```
Comment (szmarczak) [inline test/stream.ts:267]: This should be `body: form`.
