### PR TITLE
Clear `socket` timeout on error

### LINKED ISSUE #631: Intermittent uncaught errors
With got version 9.2.2, I'm seeing `timed-out` crash occasionally with an unhandled `error` event. I'm using the promise API, not the stream-based one, so I expect this event to always be turned into a promise rejection.

```
TimeoutError: Timeout awaiting 'response' for 2000ms 
  at Immediate.timeoutHandler (/node_modules/got/source/timed-out.js:39:25) 
```

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #631

### CODE REVIEW

File: test/timeout.js [hunk 1]
```diff
@@ -458,3 +458,17 @@ test('no more timeouts after an error', async t => {
...
+
+	const promise = got(s.url, {
+		timeout: {socket: requestTimeout},
+		retry: 0
+	}).on('request', request => {
+		request.emit('error', new Error(message));
+	});
+
+	await t.throwsAsync(promise, {message});
+	await delay(10);
```
Comment (brandon93s) [inline test/timeout.js]: Consider copying the note here as well. Wasn't immediately clear why we were waiting. 

> // Wait a bit more to check if there are any unhandled errors
