### PR TITLE
Reject normalization errors with CancelableRequest

### LINKED ISSUE #1025: Incorrect url causes `.json is not a function` error
#### Describe the bug

 - Node.js version: 12.4.0
 - OS & version: Arch Linux Linux 5.4.11-arch1-1

When a url given to the got.post / got.get functions is incorrect AND the function is followed with a .json(), this error is thrown:

```
    TypeError: got.post(...).json is not a function
```

#### Actual behavior

Error is thrown (see above)

#### Expected behavior

Throw HTTP Error 404, Not found

#### Code to reproduce

```js
function test(){
  return got.get('undefined/https://jsonplaceholder.typicode.com/todos/1').json();
};

test();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

### PR DESCRIPTION
**Pull request by callmehiphop**
Closes #1025

In the event of an error being thrown during argument normalization a normal promise was being returned which prevented users from calling any of the CancelableRequest convenience methods. This changes makes it so a rejected CancelableRequest is returned instead.

#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.

### CODE REVIEW

File: test/error.ts [hunk 1]
```diff
@@ -193,6 +193,12 @@ test('errors are thrown directly when options.stream is true', t => {
 	});
 });
 
+test('normalization errors using convenience methods', async t => {
+	const error = await t.throwsAsync(got('undefined/https://example.com'));
```
Comment (szmarczak) [inline test/error.ts]:
```suggestion
	await t.throwsAsync(got('undefined/https://example.com').json().text().buffer(), 'Invalid URL');
```

File: test/error.ts [hunk 2]
```diff
@@ -193,6 +193,12 @@ test('errors are thrown directly when options.stream is true', t => {
...
+
+	t.true(error.message.includes('Invalid URL'));
```
Comment (szmarczak) [inline test/error.ts]: This line is unnecessary

File: test/error.ts (hunk 1 above)
Comment (callmehiphop) [reply test/error.ts]: Fixed!

File: test/error.ts (hunk 2 above)
Comment (callmehiphop) [reply test/error.ts]: I went ahead and removed it, PTAL!

File: test/error.ts (hunk 1 above)
Comment (szmarczak) [reply test/error.ts]: You forgot to test `.text()` and `.buffer()`. Make sure that the error message is `Invalid URL`. As in the suggestion.

Comment (callmehiphop) [reply test/error.ts]: Ah, I must have missed the `Invalid URL` part. Do you want a separate assertion for each method?

Comment (szmarczak) [reply test/error.ts]: No need to

**Comment by szmarczak** [comment]
Looks good, thanks! 🙌
