### PR TITLE
Fix Electron throwing `HTTP trailers are not supported` error

### LINKED ISSUE #461: Using useElectronNet results in error: HTTP trailers are not supported
I'm using this code to upload a file to S3:

```
const response = await got.put(urlString, {
      body: fs.readFileSync(filename),
      useElectronNet: true,
    });
``` 
And this throws an uncaughtException "HTTP trailers are not supported"

This because the response is parsed by mimic-response:  `mimicResponse(res, progressStream);`
and mimic-response uses a `knownProps` array to read values from the `IncomingMessage`.
`knownProps` props contains 'trailers' and 'rawTrailers'. When these are read from the `IncomingMessage`, this throws an error because of this code:
https://github.com/electron/electron/blob/1c0ea0286ed7f8fb9075d1a6c03c758c72e965b8/lib/browser/api/net.js#L59

mimic-response should be made aware of that it is using electron.net or got should do something to prevent the reading of these properties.

If you let me know what you'd prefer, I can make a pull request 😄

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #461

### CODE REVIEW

File: source/request-as-event-emitter.js [hunk 1]
```diff
@@ -47,13 +47,26 @@ module.exports = options => {
...
+					get: (target, name) => {
+						if (name === 'trailers' || name === 'rawTrailers') {
+							return [];
+						}
+
+						const value = target[name];
+						return is.function(value) ? value.bind(target) : value;
+					}
+				});
+			}
```
Comment (sindresorhus) [inline source/request-as-event-emitter.js]: Why not just this?

```js
if (options.useElectronNet) {
	response.trailers = [];
	response.rawTrailers = [];
}
```

File: source/request-as-event-emitter.js [hunk 2]
```diff
@@ -47,13 +47,26 @@ module.exports = options => {
 
 		/* istanbul ignore next: electron.net is broken */
 		if (options.useElectronNet && process.versions.electron) {
-			const electron = global['require']('electron'); // eslint-disable-line dot-notation
+			const electron = require('electron');
```
Comment (sindresorhus) [inline source/request-as-event-emitter.js]: It was like this for a reason. It's to prevent Webpack from complaining. I guess we should add a comment about that.

Comment (szmarczak) [reply source/request-as-event-emitter.js]: IDK why but the "global" approach was throwing an error for me. I'll try that again.

File: source/request-as-event-emitter.js (hunk 1 above)
Comment (sindresorhus) [reply source/request-as-event-emitter.js]: I see. You could use `Object.defineProperty`, but I guess this is safer.

File: source/request-as-event-emitter.js [hunk 3]
```diff
@@ -47,13 +47,26 @@ module.exports = options => {
...
 			fn = electron.net || electron.remote.net;
 		}
 
 		let timings;
 		const cacheableRequest = new CacheableRequest(fn.request, options.cache);
 		const cacheReq = cacheableRequest(options, response => {
+			if (options.useElectronNet) {
```
Comment (sindresorhus) [inline source/request-as-event-emitter.js]: Can you add a comment with a link to the Electron issue this fixes?

Comment (szmarczak) [reply source/request-as-event-emitter.js]: Yeah, I'll do.

File: source/request-as-event-emitter.js (hunk 2 above)
Comment (szmarczak) [reply source/request-as-event-emitter.js]: This is what I get:
```js
(node:8174) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: global.require is not a function
```

Comment (szmarczak) [reply source/request-as-event-emitter.js]: Hmm... Smart :P

File: source/request-as-event-emitter.js [hunk 4]
```diff
@@ -1,4 +1,6 @@
 'use strict';
+/* istanbul ignore next: webpack only */
+const r = ({x: require})['yx'.slice(1)];
```
Comment (sindresorhus) [inline source/request-as-event-emitter.js]: This is only used in one place, so just put it inline with the function call at line 50.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?
