### PR TITLE
Fix `response` event not being emitted on cache verify request

### LINKED ISSUE #1287: Request hangs up with GOT v11
#### Describe the bug

 - Node.js version: 12.16.3
 - OS & version: Debian Buster

#### Actual behavior
Request gets stuck while downloading.
...

#### Expected behavior
Request should either timeout or give correct response
...

#### Code to reproduce

```js

const agent = {
  http: new http.Agent({ keepAlive: true }),
  https: new https.Agent({ keepAlive: true })
};

var requestOptions = {
    timeout: 45000, // milliseconds
    responseType: 'buffer',
    retry: 0,
    maxRedirects: 5,
    dnsCache: false,
    headers: {
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'Accept-Language': 'en-US,en;q=0.5'
    },
    shared: false,
    agent,
    cache: cacheStore
  };

got.get("https://www.empiresuppliesonline.co.uk/ekmps/shops/empiresupplies/images/Waring-X-Prep-Kitchen-Blender-2523-p.jpg", requestOptions);

I am using https://www.npmjs.com/package/improved-cacheable-request as cache store.

Please note I download around 500 such URLs per minute but the issue majorly happens with this given domain name.

``` 

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

### PR DESCRIPTION
**Pull request by Giotino**
~~That's only a workaround, a real solution is still WIP (this PR will be updated).~~

#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.

Fixes #1287

### CODE REVIEW

File: test/cache.ts [hunk 1]
```diff
@@ -310,3 +310,31 @@ test('does not hang on huge response', withServer, async (t, server, got) => {
...
+		}
+	});
+
+	const cache = new Map();
+
+	const originalResponse = await got({cache});
+
+	t.false(originalResponse.isFromCache);
+	t.is(originalResponse.body, body);
+	t.is(cache.size, 1);
```
Comment (szmarczak) [inline test/cache.ts:334]: This test fails with a value of `0`, not `1`.

File: test/cache.ts [hunk 2]
```diff
@@ -310,3 +310,31 @@ test('does not hang on huge response', withServer, async (t, server, got) => {
...
 	t.is(body.length, bufferSize * times);
 });
+
+test('cached response ETag', withServer, async (t, server, got) => {
+	const etag = 'foobar';
+	const body = 'responseBody';
+
+	server.get('/', (request, response) => {
+		if (request.headers['if-none-match'] === etag) {
+			response.writeHead(304, {ETag: 'asdf'});
```
Comment (szmarczak) [inline test/cache.ts:320]: I don't think you should change the etag header if you reply with 304...

File: test/cache.ts (hunk 1 above)
Comment (Giotino) [reply test/cache.ts:334]: I know, I wrote it in the commit message.
I think it's some kind of bug of got and not of the test.

File: test/cache.ts (hunk 2 above)
Comment (Giotino) [reply test/cache.ts:320]: Yes, it was a copy and paste from the line of the 200 answer. I am going to remove it

File: test/cache.ts (hunk 1 above)
Comment (Giotino) [reply test/cache.ts:334]: When the first request `await got({cache})` is resolved, the cache is not immediately populated with the response.

Comment (Giotino) [reply test/cache.ts:334]: From `cacheable-request` documentation:
> .on('request', request)
> request event to get the request object of the request.
>
> This event will only fire if an HTTP request is actually made, not when a response is retrieved from cache. However, you should always handle the request event to end the request and handle any potential request errors.

"you should always handle the request event to end the request"
So i ended the request as suggested and it worked. Also the the promise is now resolved with the actual response and not the request.

File: source/core/index.ts [hunk 3]
```diff
@@ -1318,7 +1318,7 @@ export default class Request extends Duplex implements RequestEvents<Request> {
 			cacheRequest.once('error', reject);
 			cacheRequest.once('request', r => {
 				request = r;
-				resolve(r);
+				r.end();
```
Comment (szmarczak) [inline source/core/index.ts:1321]: Why this change? This seems to be incorrect.

Comment (Giotino) [reply source/core/index.ts:1321]: I haven't read a lot of got code, I'm still learning how it works internally.
Can you explain me what's the difference between resolving that promise with a request rather than a response?

Comment (Giotino) [reply source/core/index.ts:1321]: > If yes the correct solution should be putting `resolve(r)` after the `r.end()`.

I read the `_onRequest` code and that solution is wrong, tomorrow I'll look into it.

Comment (Giotino) [reply source/core/index.ts:1321]: In `cacheable-request` the `request` and `response` events could be emitted before the cache write.

Request event: https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L156
Response event: https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L146
Cache write: https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L131

I can't find any solution to adapt this behavior to got.
I see only 2 options:
The first is to leave it as it is, close (in terms of time) requests might not have the cache.
The second would be working on adding a "cache write" event to `cacheable-request`, to ensure that the got request is resolved only when the cache is successfully written.

I think the best would be the first one, the cache is not a "must", I don't see any problem by having to do a request 2 times (if close in time). I would prefer the speed of the got request, by not waiting a local or __remote__ cache storage.

**Comment by adityapatadia** [comment]
Any thoughts on merging this one? #1287 is pending due to this I think?

**Comment by szmarczak** [comment]
Good job @Giotino! :raised_hands:

**Comment by adityapatadia** [comment]
I think this is still not available in `11.4.0`. Is this planned for future release?

**Comment by szmarczak** [comment]
> Is this planned for future release?

Yes. I'll try to make another one ASAP.
