### PR TITLE
Fix resource leak by removing abort event listeners on destroy

### LINKED ISSUE #2160: Resource leak when (re-)using an abort signal
#### Describe the bug

 - Node.js version: v16.17.1
 - OS & version: Debian 5.10.140-1

When re-using an abort controller for multiple got requests a significant amount of memory is retained by the `AbortSignal` through got. The main reason for this (I think) is that the `Request` instance adds an event listener for the `abort`event on the passed signal where the event handler refers back to the request. The event handler is never removed so the signal retains a reference to the `Request` instance for as long as it lives.

#### Actual behavior

The code to reproduce below downloads and discards a 1MB file in a loop. The loop exists when the abort signal is aborted via ctrl-c. The same abort signal is passed to got to cancel the in-progress download. The heap profile screenshot below shows how a large chunk of memory is retained via the callback context of an event listener coming from here:
https://github.com/sindresorhus/got/blob/main/source/core/index.ts#L254

screenshot_20221010_221207

#### Expected behavior

Memory is released after the request completes.

#### Code to reproduce

```js
import got from 'got';

const abortController = new AbortController();

process.on('SIGINT', function () {
  abortController.abort();
});

async function main() {
  while (!abortController.signal.aborted) {
    await got.get(
      'https://ia902805.us.archive.org/14/items/1mbFile/1mb.mp4',
      {
        signal: abortController.signal,
      }
    ).buffer();
  }
}

main().then(() => console.log('Bye')).catch((e) => {
  if (e.constructor.name !== 'AbortError') {
    console.error(e);
  }
});
```

#### Checklist

- [*] I have read the documentation.
- [*] I have tried my code with the latest version of ~~Node.js~~ and Got.

### PR DESCRIPTION
**Pull request by marcelmeulemans**
This change removes the event listener callback that is added to the passed `AbortSignal` when the *got* instance is destroyed.

I'm not entirely sure that this fix covers all clean up points. I skipped the clean up on the redirect which I think is correct but would appreciate confirmation.

Also I'd be open to adding a test to cover this but any pointer on how to test this would be appreciated!

Fixes #2160

#### Checklist

- [*] I have read the documentation.
- [*] I have included a pull request description of my changes.
- [x] I have included some tests.

### CODE REVIEW

File: source/core/index.ts [hunk 1]
```diff
@@ -176,6 +176,7 @@ export default class Request extends Duplex implements RequestEvents<Request> {
 	private _triggerRead: boolean;
 	declare private _jobs: Array<() => void>;
 	private _cancelTimeouts: () => void;
+	private readonly _removeListeners: () => void;
```
Comment (szmarczak) [inline source/core/index.ts:179]:
```suggestion
	private _removeListeners: () => void;
```

File: source/core/index.ts [hunk 2]
```diff
@@ -247,13 +249,20 @@ export default class Request extends Duplex implements RequestEvents<Request> {
...
+		if (this.options.signal) {
+			const abort = () => {
+				this.destroy(new AbortError(this));
+			};
 
-		this.options.signal?.addEventListener('abort', () => {
-			this.destroy(new AbortError(this));
-		});
+			if (this.options.signal.aborted) {
+				abort();
```
[the remark this answers is not in the document]
Comment (marcelmeulemans) [reply source/core/index.ts:258]: Good catch, there would still be leak for an already aborted signal. Are you sure about the return though because the `if (is.nodeStream(body)) {` branch on line 270 is also not executed anymore? Alternatively the `addEventListener` would go in an `else`.

File: source/core/index.ts (hunk 1 above)
Comment (marcelmeulemans) [reply source/core/index.ts:179]: `xo` does not like this suggestion without reassigning `_removeListeners` somewhere. Should it be reset to `noop` somewhere?

File: source/core/index.ts [hunk 3]
```diff
@@ -199,6 +200,7 @@ export default class Request extends Duplex implements RequestEvents<Request> {
 		this._unproxyEvents = noop;
 		this._triggerRead = false;
 		this._cancelTimeouts = noop;
+		this._removeListeners = noop;
```
Comment (sindresorhus) [inline source/core/index.ts:203]: @szmarczak Unrelated, but why are we assigning here instead of just giving the class fields a new value directly?

Comment (szmarczak) [reply source/core/index.ts:203]: I guess I'm just not used to this. I agree, it looks much better if the values were given directly :)

File: source/core/index.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (marcelmeulemans) [reply source/core/index.ts]: Done

**Review by szmarczak — APPROVED** [review]

**Comment by marcelmeulemans** [comment]
Any action required from my end here?

I thought of a unit test for this and came up with this: https://github.com/marcelmeulemans/got/commit/d150e4f77a5fd72babf199a8056313921eb6689a
It works well, but the approach is not great because it is kind of based on knowledge of how the controller is used internally. I can squash it in if you guys want.

**Comment by sindresorhus** [comment]
> I can squash it in if you guys want.

That would be great 👍

**Comment by sindresorhus** [comment]
Thanks :)
