### PR TITLE
Fix Webpack warnings

### LINKED ISSUE #742: Tricking webpack makes webpack spit out ugly warnings
#### What would you like to discuss?
I use `got 9.6.0` with `webpack 4.29.6` and target a node application. Webpack throws this ugly warning 
```
WARNING in ./node_modules/got/source/request-as-event-emitter.js 72:18-25
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
The reason for this is the following tricky code in request-as-event-emitter.js line 42
``` js
  const r = ({x: require})['yx'.slice(1)]; // Trick webpack
  const electron = r('electron');
```
If I replace those lines with
``` js
  const electron = require('electron');
```
and configure webpack to treat 'electron' as an external dependency everything is fine without warnings.
Maybe this hack was necessary once, but it would nice to use something more standard that works out of the box.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #742

### CODE REVIEW

**Comment by sindresorhus** [comment]
mod => moduleObject

request => moduleId

any => unknown

**Comment by sindresorhus** [comment]
Have you tested that this doesn't introduce any warnings when using Got with Webpack?

File: source/utils/dynamic-require.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export default (moduleId: string, moduleObject: NodeModule = module): unknown => {
```
Comment (sindresorhus) [inline source/utils/dynamic-require.ts]: While `= module` works here because it's called in the same package, it's not technically correct, as you're now requiring from the location of this file and not the callers. There should not be a default argument here and `module` should always be required to be passed.

Comment (szmarczak) [reply source/utils/dynamic-require.ts]: I get it. Will fix.

**Comment by szmarczak** [comment]
Tested, the error is gone! :D

I don't have much Webpack experience, so I must have imported it improperly (by copying the `dist` folder and the `node_modules` one - I don't know how to import it locally):

```js
WARNING in ./node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression
```

otherwise no errors :) On Chrome runs as expected, with minimal support :P

**Comment by sindresorhus** [comment]
We should maybe move this logic to https://github.com/sindresorhus/require-fool-webpack so we can reuse it in other packages like `keyv` (per above).
