### PR TITLE
Some `beforeRequest` edited options are discarded

### LINKED ISSUE #1292: Can't use agent in beforeHook
If I put:

```ts
hooks: {
  beforeRequest: [
    opts => {
      const proxies = [];
      const proxy = proxies[Math.floor(Math.random() * proxies.length)];
      opts.agent = new HttpsProxyAgent(proxy) as any;
    }
  ]
}
```

I get:

```
RequestError: The `options.agent` object can contain only `http`, `https` or `http2` properties
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762520)
    at f.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:810576)
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762069)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:746276
onError aJ [RequestError]: The `options.agent` object can contain only `http`, `https` or `http2` properties
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762520)
    at f.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:810576)
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762069)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:746276 {
  code: undefined,
  timings: undefined
}
```

and if I put:

```ts
hooks: {
  beforeRequest: [
    opts => {
      const proxies = [];
      const proxy = proxies[Math.floor(Math.random() * proxies.length)];
      opts.agent = {
        https: new HttpsProxyAgent(proxy) as any;
      }
    }
  ]
}
```

I get:

```
RequestError: The "options.agent" property must be one of type Agent-like Object, undefined or false. Received object
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826811)
    at new j.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:877067)
    at f.exports (/Users/devchris/Documents/code/nodejs/project/build.js:1:875709)
    at async l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826350)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:810877
onError aJ [RequestError]: The "options.agent" property must be one of type Agent-like Object, undefined or false. Received object
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826811)
    at new j.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:877067)
    at f.exports (/Users/devchris/Documents/code/nodejs/project/build.js:1:875709)
    at async l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826350)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:810877 {
  code: 'ERR_INVALID_ARG_TYPE',
  timings: undefined
}
```

Its only happening with the option http2: true, with false, you can pass the agent like that: `opts.agent = new HttpsProxyAgent(proxy) as any;` even if the typing is wrong

And by the way the typing is broken too...

Thanks

### PR DESCRIPTION
**Pull request by Giotino**
Currently he edits of `options.agent` and `options.url` made in `beforeRequest` are discarded.

This PR simply read `agent` and `url` after `beforeRequest` hooks.

#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.

Fixes #1292

### CODE REVIEW

File: source/core/index.ts [hunk 1]
```diff
@@ -1254,7 +1254,7 @@ export default class Request extends Duplex implements RequestEvents<Request> {
 
 	async _makeRequest(): Promise<void> {
 		const {options} = this;
-		const {url, headers, request, agent, timeout} = options;
```
Comment (szmarczak) [inline source/core/index.ts:1257]: Can't we just place the line above after the beforeRequest hooks have been called?

Comment (Giotino) [reply source/core/index.ts:1257]: I didn't want to make more changes than necessary, but it's ok if `timeout` and `request` should be restored with the `beforeRequest` ones.

**Comment by Giotino** [comment]
Also i wanted to talk about the "unix socket url parsing" before the request.

Documentation for `beforeRequest`:
> Got will make no further changes to the request before it is sent

But this code is modifying some options, after `beforeRequest` but before the request.
https://github.com/sindresorhus/got/blob/master/source/core/index.ts#L1360,L1372

I think this code should be moved before `beforeRequest`.

**Comment by szmarczak** [comment]
> I think this code should be moved before beforeRequest.

No, it should stay where it is. It just translates UNIX hostname to Node.js native options.

File: source/core/index.ts [hunk 2]
```diff
@@ -1289,6 +1290,8 @@ export default class Request extends Duplex implements RequestEvents<Request> {
 			}
 		}
 
+		const {agent, request, timeout, url} = options;
```
Comment (szmarczak) [inline source/core/index.ts:1293]:
```suggestion
		const {agent, headers, request, timeout, url} = options;
```

**Comment by szmarczak** [comment]
https://travis-ci.com/github/sindresorhus/got/jobs/340837947#L756

```
$ node --version
v14.3.0

...

  ✖ Timed out while running tests
  1 tests were pending in test/http.ts
  ◌ http.ts › throws an error if the server aborted the request
```

Can you figure out why it fails please?

**Comment by Giotino** [comment]
> https://travis-ci.com/github/sindresorhus/got/jobs/340837947#L756
> 
> ```
> $ node --version
> v14.3.0
> 
> ...
> 
>   ✖ Timed out while running tests
>   1 tests were pending in test/http.ts
>   ◌ http.ts › throws an error if the server aborted the request
> ```
> 
> Can you figure out why it fails please?

Even the `master` branch is failing the same test, for the same reason.
I'm trying to figure out why.

**Comment by Giotino** [comment]
By doing some test it seems to happen only with Node.JS >= 14.3.0

**Comment by Giotino** [comment]
These Node.JS commit (merged into 14.3.0) can be relevant to this issue:
https://github.com/nodejs/node/commit/b634d4b000
https://github.com/nodejs/node/commit/cc5c8e039d
