### PR TITLE
`beforeRetry` allows stream body if different from original

### LINKED ISSUE #1500: beforeRetry hook does not read form-data stream
#### Describe the bug

 - Node.js version: 14.13.0
 - OS & version: macOS 10.15.7
 - got: 11.7.0

Using `form-data` to do a post request the beforeRetry hook reads the form-data stream but ignores subsequent retries.
Can this be done without having to buffer the form into memory?

#### Code to reproduce
**Server:**
```js
const express = require('express')
const multer = require('multer');

const app = express()
app.use(multer().any());

const port = 3000
app.use(express.urlencoded({extended: true}))
app.post('/', (req, res) => res.status(500).end())
app.listen(port, () => console.log(`http://localhost:${port}`));
```

**Request:**
```js
const fs = require('fs');
const got = require('got');
const formData = require('form-data');

function getBody() {
	var form = new formData();
	form.append('field1', 'field1');
	form.append('file', fs.createReadStream('./big_file.webm'), 'filename');
	return form;
}

(async () => {
	const form = getBody();
	await got.post('http://localhost:3000', {
		body: form,
		retry: {
			limit: 3,
			methods: ['POST'],
		},
		headers: {
			'content-type': `multipart/form-data; boundary=${form.getBoundary()}`
		},
      hooks: {
        beforeRetry: [
        (options, error, retryCount) => {
			console.log('beforeRetry hook: error %s - count %s', error?.response?.statusCode, retryCount);
			options.body = getBody();
          },
        ],
      },
	}).on('uploadProgress', console.log)
})().catch(err => {
	console.error(err.message);
});
```

**Output:**

```bash
(...)
{ percent: 0.9999993776361802, transferred: 93193020, total: 93193078 }                                       │
{ percent: 1, transferred: 93193078, total: 93193078 }                                                        │
beforeRetry hook: error 500 - count 1                                                                         │
Response code 500 (Internal Server Error) 
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

### PR DESCRIPTION
**Pull request by Giotino**
#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.

Fixes #1500

### CODE REVIEW

File: source/as-promise/index.ts [hunk 1]
```diff
@@ -152,8 +152,10 @@ export default function asPromise<T>(normalizedOptions: NormalizedOptions): Canc
 
 			request.once('error', onError);
 
+			const previusBody = request.options.body;
```
Comment (sindresorhus) [inline source/as-promise/index.ts:155]:
```suggestion
			const previousBody = request.options.body;
```

File: test/hooks.ts [hunk 2]
```diff
@@ -451,6 +452,43 @@ test('beforeRetry allows modifications', withServer, async (t, server, got) => {
...
+		if (request.headers.foo) {
+			response.send('test');
+		} else {
+			response.statusCode = 500;
+		}
+
+		response.end();
+	});
+
+	const genBody = () => {
```
Comment (sindresorhus) [inline test/hooks.ts:466]: Don't use abbreviations.

File: source/as-promise/index.ts (hunk 1 above)
Comment (Giotino) [reply source/as-promise/index.ts:155]: Little typo 😄
