### PR TITLE
Loosen unnecessary restrictions on the `body` option

### LINKED ISSUE #381: Regression in 7.0.0 options processing
#217 loosened unnecessary restrictions on `body` option that were discussed in #212 and allowed it to be an object that is generally considered *plain* by a developer, i.e. not a *complex* object - a buffer or a stream, which are processed differently. 

#297 introduced a regression that imposed a restriction on `body` option again.

Excessive sanitization results from the use of `is-plain-obj` and restricts `body` object prototype chain to contain only  `Object.prototype` or `null`. This restriction results in counter-intuitive behaviour and requires a developer to use tricks like `Object.assign({}, obj)` instead of not doing them, even if an object is perceived as 'plain' (in my experience it was `querystring.parse()`) .

More importantly, this results in breaking changes that aren't reflected in change logs. The restrictions were dropped for a good reason, and resulting behaviour has been already relied on by package users. Now the regression just happened without an obvious reason.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #381

### CODE REVIEW

File: test/error.js [hunk 1]
```diff
@@ -26,6 +26,15 @@ test.before('setup', async () => {
 		res.end('body');
 	});
 
+	s.on('/body', (req, res) => {
+		const body = [];
+		req.on('data', chunk => {
+			body.push(chunk);
+		}).on('end', () => {
+			res.end(Buffer.concat(body).toString());
+		});
```
Comment (sindresorhus) [inline test/error.js]: Use `get-stream` here for simplicity

File: test/error.js [hunk 2]
```diff
@@ -54,17 +63,27 @@ test('dns message', async t => {
 
 test('options.body error message', async t => {
 	const err = await t.throws(got(s.url, {body: {}}));
-	t.regex(err.message, /The `body` option must be a stream\.Readable, string or Buffer/);
+	t.is(err.message, 'The `body` option must be a stream.Readable, string or Buffer');
```
Comment (sindresorhus) [inline test/error.js]: We should change all of the `t.throws` assertions to the new format. Should not be done in this PR though. Just a note to myself.

File: test/error.js [hunk 3]
```diff
@@ -54,17 +63,27 @@ test('dns message', async t => {
...
-	t.regex(err.message, /The `body` option must be a plain Object when the `form` option is used/);
+	t.is(err.message, 'The `body` option must be an Object when the `form` option is used');
+});
+
+test('no plain object restriction on body', async t => {
+	function CustomObject() {
+		this.a = 123;
+	}
+
+	const {body} = (await got(`${s.url}/body`, {body: new CustomObject(), json: true}));
```
Comment (sindresorhus) [inline test/error.js]: You don't need parens around `await`

File: test/error.js (hunk 2 above)
Comment (szmarczak) [reply test/error.js]: Ok, so after this gets merged I'll do another PR for that.

File: test/error.js (hunk 3 above)
Comment (szmarczak) [reply test/error.js]: Yup. Forgot because before I did `const body = (...).body` then I used `const { body } = ...` :)
