### PR TITLE
Fix `Stream.pipeline(...)` usage and properly detect aborted requests

### LINKED ISSUE #907: Promise never resolved/ rejected if connection is accepted but socket is terminated
#### Describe the bug

 - Node.js version: N/A
 - OS & version: N/A

#### Actual behavior

Promise is never resolved/ rejected.

#### Expected behavior

Promise resolved/ rejected.

#### Code to reproduce

https://repl.it/@gajus/CapitalDangerousMultitasking

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #907

### CODE REVIEW

File: source/request-as-event-emitter.ts [hunk 1]
```diff
@@ -208,7 +208,22 @@ export default (options: NormalizedOptions, input?: TransformStream) => {
...
+				}
+
+				// No need to attach an error handler here,
+				// as `stream.pipeline(...)` doesn't remove this handler
+				// to allow stream reuse.
+
+				request.emit('upload-complete');
+			};
+
+			request.on('error', onError);
```
Comment (szmarczak) [inline source/request-as-event-emitter.ts]: It needs to be here in case `timer(...)` or `timedOut(...)` throws...

**Comment by sindresorhus** [comment]
The timeout tests seem to fail on Node.js 10. I confirmed this locally too.
