### PR TITLE
Don't break the default behavior when using custom retry function

### LINKED ISSUE #753: Custom `retry.retries` function unexpectedly breaks `statusCode` and other conditional retries
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/got/issues/753)

Since `retry.statusCodes` and `retry.errorCodes` option support is implemented as part of the default `retries` function, those options are incompatible with custom retry function. Moreover even default `statusCodes` become not working so you get retries for HTTP 401, for example.
This is not quite obvious and documentation says nothing about that.

I think this is a bug to be fixed or at least it should be stated in readme.

> There is a $60.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/got/issues/753).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/got/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by szmarczak**
#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.
- [x] If it's a new feature, I have included documentation updates.

Fixes #753

### CODE REVIEW

File: source/utils/types.ts [hunk 1]
```diff
@@ -67,20 +67,22 @@ export interface Response extends http.IncomingMessage {
 	request: { options: NormalizedOptions };
 }
 
-export type RetryFunction = (retry: number, error: Error | GotError | ParseError | HTTPError | MaxRedirectsError) => number;
+export type RetryFunction = (retry: number, retryOptions: NormalizedRetryOptions, error: Error | GotError | ParseError | HTTPError | MaxRedirectsError, computedValue: number) => number;
```
Comment (sindresorhus) [inline source/utils/types.ts]: I think we need a clearer name for the `retry` argument.

And would be good to add doc comments for at least `computedValue` as it's not clear to be what that is.

There's a lot of arguments now. Since it's a breaking change anyway, maybe we should just pass in one object as an argument?

File: readme.md [hunk 2]
```diff
@@ -322,20 +322,21 @@ This also accepts an `object` with the following fields to constrain the duratio
 
 Type: `number | object`<br>
 Default:
-- retries: `2`
+- limit: `2`
+- retryFunction: `(iteration, retryOptions, error, computedValue) => computedValue`
```
Comment (sindresorhus) [inline readme.md]: I think we should use a clearer name here. Maybe `delay()`, `calculateDelay()`, or `getDelay()`. Other suggestions?

File: readme.md [hunk 3]
```diff
@@ -322,20 +322,21 @@ This also accepts an `object` with the following fields to constrain the duratio
...
+An object representing `limit`, `retryFunction`, `methods`, `statusCodes`, `maxRetryAfter` and `errorCodes` fields for maximum iteration count, retry handler, allowed methods, allowed status codes, maximum [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) time and allowed error codes.
 
 If `maxRetryAfter` is set to `undefined`, it will use `options.timeout`.<br>
 If [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header is greater than `maxRetryAfter`, it will cancel the request.
 
 Delays between retries counts with function `1000 * Math.pow(2, retry) + Math.random() * 100`, where `retry` is attempt number (starts from 1).
 
-The `retries` property can be a `number` or a `function` with `retry` and `error` arguments. The function must return a delay in milliseconds (`0` return value cancels retry).
+The `retryFunction` property is a `function` with `iteration`, `retryOptions`, `error` and `computedValue` arguments. The function must return a delay in milliseconds (`0` return value cancels retry).
```
Comment (sindresorhus) [inline readme.md]: Would be good to explain what the different arguments are and what they are for. Same in the code as a doc comment.

File: source/utils/types.ts (hunk 1 above)
Comment (szmarczak) [reply source/utils/types.ts]: > I think we need a clearer name for the retry argument.

`iterationCount`?

> There's a lot of arguments now. Since it's a breaking change anyway, maybe we should just pass in one object as an argument?

Sounds good.

File: readme.md (hunk 2 above)
Comment (szmarczak) [reply readme.md]: I'd go with `calculateDelay`.

File: source/utils/types.ts (hunk 1 above)
Comment (sindresorhus) [reply source/utils/types.ts]: Is it the number of retries including the original try or not? In p-retry I use `attemptNumber`, but that including the original try. https://github.com/sindresorhus/p-retry

Comment (szmarczak) [reply source/utils/types.ts]: It is. What about `attemptCount`? Or just plural: `attempts`?

Comment (sindresorhus) [reply source/utils/types.ts]: > attemptCount

👍

File: readme.md (hunk 2 above)
Comment (sindresorhus) [reply readme.md]: 👍

File: readme.md [hunk 4]
```diff
@@ -322,20 +322,21 @@ This also accepts an `object` with the following fields to constrain the duratio
...
 - maxRetryAfter: `undefined`
 - errorCodes: `ETIMEDOUT` `ECONNRESET` `EADDRINUSE` `ECONNREFUSED` `EPIPE` `ENOTFOUND` `ENETUNREACH` `EAI_AGAIN`
 
-An object representing `retries`, `methods`, `statusCodes`, `maxRetryAfter` and `errorCodes` fields for the time until retry, allowed methods, allowed status codes, maximum [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) time and allowed error codes.
+An object representing `limit`, `retryFunction`, `methods`, `statusCodes`, `maxRetryAfter` and `errorCodes` fields for maximum iteration count, retry handler, allowed methods, allowed status codes, maximum [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) time and allowed error codes.
```
Comment (sindresorhus) [inline readme.md]: `iteration` => `retry`
